const NORMAL_BARBARIAN = [{"image":"http://www.d2mantix.com/diablo2img/jawbonecap.JPG","name":"El Gorro Mandibula","originalName":"Jawbone Cap","codeName":"jawbonecap","tcNumber":60,"attributes":["Tipo de Objeto: Yelmos","Defensa: 10-15","Durabilidad: 25"],"itemType":"helm","itemClass":"normal","requiredStrength":25,"requiredLevel":3,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/fangedhelm.JPG","name":"El Yelmo Canino","originalName":"Fanged Helm","codeName":"fangedhelm","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 15-20","Durabilidad: 35"],"itemType":"helm","itemClass":"normal","requiredStrength":35,"requiredLevel":6,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/hornedhelm.JPG","name":"El Yelmo Astado","originalName":"Horned Helm","codeName":"hornedhelm","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 25-30","Durabilidad: 45"],"itemType":"helm","itemClass":"normal","requiredStrength":45,"requiredLevel":12,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/assualthelm.JPG","name":"El Casco de Asalto","originalName":"Assault Helmet","codeName":"assaulthelmet","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 30-35","Durabilidad: 50"],"itemType":"helm","itemClass":"normal","requiredStrength":55,"requiredLevel":15,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/avengerguard.JPG","name":"El Guardia Vengador","originalName":"Avenger Guard","codeName":"avengerguard","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 35-50","Durabilidad: 55"],"itemType":"helm","itemClass":"normal","requiredStrength":65,"requiredLevel":18,"character":"barbarian","sockets":3}]

const EXCEPTIONAL_BARBARIAN = [{"image":"http://www.d2mantix.com/diablo2img/jawbonecap.JPG","name":"El Visor Mandibula","originalName":"Jawbone Visor","codeName":"jawbonevisor","tcNumber":33,"attributes":["Tipo de Objeto: Yelmos","Defensa: 55-68","Durabilidad: 25"],"itemType":"helm","itemClass":"exceptional","requiredStrength":58,"requiredLevel":25,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/avengerguard.JPG","name":"El Guardia Criminal","originalName":"Slayer Guard","codeName":"slayerguard","tcNumber":54,"attributes":["Tipo de Objeto: Yelmos","Defensa: 93-120","Durabilidad: 55"],"itemType":"helm","itemClass":"exceptional","requiredStrength":118,"requiredLevel":40,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/assualthelm.JPG","name":"El Casco Despiadado","originalName":"Savage Helmet","codeName":"savagehelmet","tcNumber":51,"attributes":["Tipo de Objeto: Yelmos","Defensa: 85-98","Durabilidad: 50"],"itemType":"helm","itemClass":"exceptional","requiredStrength":103,"requiredLevel":32,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/hornedhelm.JPG","name":"La Mascara Furia","originalName":"Rage Mask","codeName":"ragemask","tcNumber":42,"attributes":["Tipo de Objeto: Yelmos","Defensa: 78-90","Durabilidad: 45"],"itemType":"helm","itemClass":"exceptional","requiredStrength":88,"requiredLevel":29,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/fangedhelm.JPG","name":"El Yelmo Leon","originalName":"Lion Helm","codeName":"lionhelm","tcNumber":39,"attributes":["Tipo de Objeto: Yelmos","Defensa: 63-75","Durabilidad: 35"],"itemType":"helm","itemClass":"exceptional","requiredStrength":73,"requiredLevel":29,"character":"barbarian","sockets":3}]

const ELITE_BARBARIAN = [{"image":"http://www.d2mantix.com/diablo2img/assualthelm.JPG","name":"La Corona del Conquistador","originalName":"Conqueror Crown","codeName":"conquerorcrown","tcNumber":81,"attributes":["Tipo de Objeto: Yelmos","Defensa: 114-159","Durabilidad: 50"],"itemType":"helm","itemClass":"elite","requiredStrength":174,"requiredLevel":60,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/avengerguard.JPG","name":"La Corona Guardiana","originalName":"Guardian Crown","codeName":"guardiancrown","tcNumber":87,"attributes":["Tipo de Objeto: Yelmos","Defensa: 117-168","Durabilidad: 55"],"itemType":"helm","itemClass":"elite","requiredStrength":196,"requiredLevel":65,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/fangedhelm.JPG","name":"El Visor Furia","originalName":"Fury Visor","codeName":"furyvisor","tcNumber":66,"attributes":["Tipo de Objeto: Yelmos","Defensa: 105-150","Durabilidad: 35"],"itemType":"helm","itemClass":"elite","requiredStrength":129,"requiredLevel":49,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/hornedhelm.JPG","name":"El Yelmo Destructor","originalName":"Destroyer Helm","codeName":"destroyerhelm","tcNumber":75,"attributes":["Tipo de Objeto: Yelmos","Defensa: 111-156","Durabilidad: 45"],"itemType":"helm","itemClass":"elite","requiredStrength":151,"requiredLevel":54,"character":"barbarian","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/jawbonecap.JPG","name":"El Yelmo de la Matanza","originalName":"Carnage Helm","codeName":"carnagehelm","tcNumber":60,"attributes":["Tipo de Objeto: Yelmos","Defensa: 102-147","Durabilidad: 25"],"itemType":"helm","itemClass":"elite","requiredStrength":106,"requiredLevel":45,"character":"barbarian","sockets":3}]

module.exports = {
    NORMAL_BARBARIAN,
    EXCEPTIONAL_BARBARIAN,
    ELITE_BARBARIAN
}