const NORMAL_CROSSBOWS = [{"image":"http://www.d2mantix.com/diablo2img/lightcrossbow.JPG","name":"Ballesta Ligera","originalName":"Light Crossbow","codeName":"lightcrossbow","tcNumber":6,"attributes":["Daño 2 manos: 6 a 9 (7.5 Media) Rango (0)","Velocidad: [-10]"],"itemType":"crossbow","itemClass":"normal","requiredStrength":21,"requiredDexterity":27,"sockets":3},{"image":"http://www.d2mantix.com/diablo2img/crossbow.JPG","name":"Ballesta","originalName":"Crossbow","codeName":"crossbow","tcNumber":15,"attributes":["Daño 2 manos: 9 a 16 (12.5 Media) Rango (0)","Velocidad: [0]"],"itemType":"crossbow","itemClass":"normal","requiredStrength":40,"requiredDexterity":33,"sockets":4},{"image":"http://www.d2mantix.com/diablo2img/heavycrossbow.JPG","name":"Ballesta Pesada","originalName":"Heavy Crossbow","codeName":"heavycrossbow","tcNumber":24,"attributes":["Daño 2 manos: 14 a 26 (20 Media) Rango (0)","Velocidad: [10]"],"itemType":"crossbow","itemClass":"normal","requiredStrength":60,"requiredDexterity":40,"sockets":6},{"image":"http://www.d2mantix.com/diablo2img/repeatingcrossbow.JPG","name":"Ballesta con Repeticion","originalName":"Repeating Crossbow","codeName":"repeatingcrossbow","tcNumber":33,"attributes":["Daño 2 manos: 6 a 12 (9 Media) Rango (0)","Velocidad: [-40]"],"itemType":"crossbow","itemClass":"normal","requiredStrength":40,"requiredDexterity":50,"sockets":5}]

const EXCEPTIONAL_CROSSBOWS = [{"image":"http://www.d2mantix.com/diablo2img/lightcrossbow.JPG","name":"Ballesta","originalName":"Arbalest","codeName":"arbalest","tcNumber":36,"attributes":["Daño 2 manos: 14 a 27 (20.5 Media) Rango (0)","Velocidad: [-10]"],"itemType":"crossbow","itemClass":"exceptional","requiredStrength":52,"requiredDexterity":61,"requiredLevel":22,"sockets":3},{"image":"http://www.d2mantix.com/diablo2img/crossbow.JPG","name":"Ballesta de Asedio","originalName":"Siege Crossbow","codeName":"siegecrossbow","tcNumber":42,"attributes":["Daño 2 manos: 20 a 42 (31 Media) Rango (0)","Velocidad: [0]"],"itemType":"crossbow","itemClass":"exceptional","requiredStrength":80,"requiredDexterity":70,"requiredLevel":25,"sockets":4},{"image":"http://www.d2mantix.com/diablo2img/heavycrossbow.JPG","name":"Ballesta Pesada","originalName":"Ballista","codeName":"ballista","tcNumber":48,"attributes":["Daño 2 manos: 33 a 55 (44 Media) Rango (0)","Velocidad: [10]"],"itemType":"crossbow","itemClass":"exceptional","requiredStrength":110,"requiredDexterity":88,"requiredLevel":25,"sockets":6},{"image":"http://www.d2mantix.com/diablo2img/repeatingcrossbow.JPG","name":"Chu-Ko-Nu","originalName":"Chu-Ko-Nu","codeName":"chu-ko-nu","tcNumber":54,"attributes":["Daño 1 mano: 14 a 32 (23 Media) Rango (0)","Velocidad: [-60]"],"itemType":"crossbow","itemClass":"exceptional","requiredStrength":80,"requiredDexterity":95,"requiredLevel":25,"sockets":5}]

const ELITE_CROSSBOWS = [{"image":"http://www.d2mantix.com/diablo2img/lightcrossbow.JPG","name":"El Arco de Perdigones","originalName":"Pellet Bow","codeName":"pelletbow","tcNumber":63,"attributes":["Daño 1 mano: 28 a 73 (50.5 Media) Rango (0)","Velocidad: [-10]"],"itemType":"crossbow","itemClass":"elite","requiredStrength":83,"requiredDexterity":155,"requiredLevel":42,"sockets":3},{"image":"http://www.d2mantix.com/diablo2img/crossbow.JPG","name":"La Ballesta de Gorgona","originalName":"Gorgon Crossbow","codeName":"gorgoncrossbow","tcNumber":69,"attributes":["Daño 2 manos: 25 a 87 (56 Media) Rango (0)","Velocidad: [0]"],"itemType":"crossbow","itemClass":"elite","requiredStrength":117,"requiredDexterity":105,"requiredLevel":50,"sockets":4},{"image":"http://www.d2mantix.com/diablo2img/heavycrossbow.JPG","name":"La Ballesta del Coloso","originalName":"Colossus Crossbow","codeName":"colossuscrossbow","tcNumber":75,"attributes":["Daño 2 manos: 32 a 91 (61.5 Media) Rango (0)","Velocidad: [10]"],"itemType":"crossbow","itemClass":"elite","requiredStrength":163,"requiredDexterity":77,"requiredLevel":56,"sockets":6},{"image":"http://www.d2mantix.com/diablo2img/repeatingcrossbow.JPG","name":"La Ballesta Demoniaca","originalName":"Demon Crossbow","codeName":"demoncrossbow","tcNumber":84,"attributes":["Daño 2 manos: 26 a 40 (33 Media) Rango (0)","Velocidad: [-60]"],"itemType":"crossbow","itemClass":"elite","requiredStrength":141,"requiredDexterity":98,"requiredLevel":63,"sockets":5}]

module.exports = {
    NORMAL_CROSSBOWS,
    EXCEPTIONAL_CROSSBOWS,
    ELITE_CROSSBOWS
}