const NORMAL_DRUID = [{"image":"http://www.d2mantix.com/diablo2img/wolfhead.JPG","name":"El Lider de los Lobos","originalName":"Wolf Head","codeName":"wolfhead","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 8-11","Durabilidad: 20"],"itemType":"helm","itemClass":"normal","requiredStrength":16,"requiredLevel":3,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/falconmask.JPG","name":"El Casco Halcon","originalName":"Hawk Helm","codeName":"hawkhelm","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 4-15","Durabilidad: 20"],"itemType":"helm","itemClass":"normal","requiredStrength":20,"requiredLevel":6,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/antlers.JPG","name":"Los Cuernos","originalName":"Antlers","codeName":"antlers","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 18-24","Durabilidad: 20"],"itemType":"helm","itemClass":"normal","requiredStrength":24,"requiredLevel":12,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/hawkhelm.JPG","name":"La Mascara Halcon","originalName":"Falkon Mask","codeName":"falkonmask","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 12-28","Durabilidad: 20"],"itemType":"helm","itemClass":"normal","requiredStrength":28,"requiredLevel":15,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/spiritmask.JPG","name":"La Mascara Espiritu","originalName":"Spirit Mask","codeName":"spiritmask","tcNumber":0,"attributes":["Tipo de Objeto: Yelmos","Defensa: 22-35","Durabilidad: 20"],"itemType":"helm","itemClass":"normal","requiredStrength":30,"requiredLevel":18,"character":"druid","sockets":3}]

const EXCEPTIONAL_DRUID = [{"image":"http://www.d2mantix.com/diablo2img/wolfhead.JPG","name":"El Yelmo Alfa","originalName":"Alpha Helm","codeName":"alphahelm","tcNumber":42,"attributes":["Tipo de Objeto: Yelmos","Defensa: 52-62","Durabilidad: 20"],"itemType":"helm","itemClass":"exceptional","requiredStrength":44,"requiredLevel":26,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/falconmask.JPG","name":"El Tocado de Grifo","originalName":"Griffon Headdress","codeName":"griffonheaddress","tcNumber":45,"attributes":["Tipo de Objeto: Yelmos","Defensa: 46-65","Durabilidad: 20"],"itemType":"helm","itemClass":"exceptional","requiredStrength":50,"requiredLevel":30,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/antlers.JPG","name":"El Disfraz Cazador","originalName":"Hunter","codeName":"hunter","tcNumber":48,"attributes":["Tipo de Objeto: Yelmos","Defensa: 67-81","Durabilidad: 20"],"itemType":"helm","itemClass":"exceptional","requiredStrength":56,"requiredLevel":29,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/hawkhelm.JPG","name":"Las Plumas Sagradas","originalName":"Sacred Feathers","codeName":"sacredfeathers","tcNumber":54,"attributes":["Tipo de Objeto: Yelmos","Defensa: 58-87","Durabilidad: 20"],"itemType":"helm","itemClass":"exceptional","requiredStrength":62,"requiredLevel":32,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/spiritmask.JPG","name":"La Mascara Totemica","originalName":"Totemik Mask","codeName":"totemikmask","tcNumber":57,"attributes":["Tipo de Objeto: Yelmos","Defensa: 73-98","Durabilidad: 20"],"itemType":"helm","itemClass":"exceptional","requiredStrength":65,"requiredLevel":41,"character":"druid","sockets":3}]

const ELITE_DRUID = [{"image":"http://www.d2mantix.com/diablo2img/wolfhead.JPG","name":"El Espiritu de Sangre","originalName":"Blood Spirit","codeName":"bloodspirit","tcNumber":63,"attributes":["Tipo de Objeto: Yelmos","Defensa: 101-145","Durabilidad: 20"],"itemType":"helm","itemClass":"elite","requiredStrength":86,"requiredLevel":46,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/falconmask.JPG","name":"El Espiritu del Sol","originalName":"Sun Spirit","codeName":"sunspirit","tcNumber":66,"attributes":["Tipo de Objeto: Yelmos","Defensa: 98-147","Durabilidad: 20"],"itemType":"helm","itemClass":"elite","requiredStrength":95,"requiredLevel":51,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/antlers.JPG","name":"El Espiritu de la Tierra","originalName":"Earth Spirit","codeName":"earthspirit","tcNumber":84,"attributes":["Tipo de Objeto: Yelmos","Defensa: 107-152","Durabilidad: 20"],"itemType":"helm","itemClass":"elite","requiredStrength":104,"requiredLevel":57,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/hawkhelm.JPG","name":"El Espiritu del Cielo","originalName":"Sky Spirit","codeName":"skyspirit","tcNumber":84,"attributes":["Tipo de Objeto: Yelmos","Defensa: 103-155","Durabilidad: 20"],"itemType":"helm","itemClass":"elite","requiredStrength":113,"requiredLevel":62,"character":"druid","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/spiritmask.JPG","name":"El Espiritu del Sueño","originalName":"Dream Spirit","codeName":"dreamspirit","tcNumber":87,"attributes":["Tipo de Objeto: Yelmos","Defensa: 109-159","Durabilidad: 20"],"itemType":"helm","itemClass":"elite","requiredStrength":118,"requiredLevel":66,"character":"druid","sockets":3}] 

module.exports = {
    NORMAL_DRUID,
    EXCEPTIONAL_DRUID,
    ELITE_DRUID
}