const { NORMAL_DAGGERS } = require("./daggers")
const { NORMAL_HELMS, EXCEPTIONAL_HELMS, ELITE_HELMS } = require("./helms")
const { NORMAL_SHIELDS, EXCEPTIONAL_SHIELDS, ELITE_SHIELDS } = require("./shields")
const { NORMAL_SCEPTERS, EXCEPTIONAL_SCEPTERS, ELITE_SCEPTERS } = require("./scepters")
const { NORMAL_ARMORS, EXCEPTIONAL_ARMORS, ELITE_ARMORS } = require("./armors")
const { NORMAL_AXES, EXCEPTIONAL_AXES, ELITE_AXES } = require("./axes")
const { NORMAL_BOWS, EXCEPTIONAL_BOWS, ELITE_BOWS } = require("./bows")
const { NORMAL_CROSSBOWS, EXCEPTIONAL_CROSSBOWS, ELITE_CROSSBOWS } = require("./crossbows")
const { NORMAL_WAR_WEAPONS, EXCEPTIONAL_WAR_WEAPONS, ELITE_WAR_WEAPONS } = require("./war_weapons")
const { NORMAL_SPEARS, EXCEPTIONAL_SPEARS, ELITE_SPEARS } = require("./spears")
const { NORMAL_SWORDS, EXCEPTIONAL_SWORDS, ELITE_SWORDS } = require("./swords")
const { NORMAL_RODS, EXCEPTIONAL_RODS, ELITE_RODS } = require("./rods")
const { NORMAL_STAFFS, EXCEPTIONAL_STAFFS, ELITE_STAFFS } = require("./staffs")
const { NORMAL_MACES, EXCEPTIONAL_MACES, ELITE_MACES, NORMAL_MACES2, EXCEPTIONAL_MACES2, ELITE_MACES2, NORMAL_MACES3, EXCEPTIONAL_MACES3, ELITE_MACES3 } = require("./maces")
const { NORMAL_AMAZON, EXCEPTIONAL_AMAZON, ELITE_AMAZON } = require("./amazon")
const { NORMAL_ASSASIN, EXCEPTIONAL_ASSASIN, ELITE_ASSASIN } = require("./assasin")
const { NORMAL_BARBARIAN, EXCEPTIONAL_BARBARIAN, ELITE_BARBARIAN } = require("./barbarian")
const { NORMAL_DRUID, EXCEPTIONAL_DRUID, ELITE_DRUID } = require("./druid")
const { NORMAL_SORCERER, EXCEPTIONAL_SORCERER, ELITE_SORCERER } = require("./sorcerer")
const { NORMAL_NECROMANCER, EXCEPTIONAL_NECROMANCER, ELITE_NECROMANCER } = require("./necromancer")
const { NORMAL_PALADIN, EXCEPTIONAL_PALADIN, ELITE_PALADIN } = require("./paladin")
const { concat } = require('lodash')

const BASE_ITEMS = concat(NORMAL_HELMS, EXCEPTIONAL_HELMS, ELITE_HELMS, 
    NORMAL_SHIELDS, EXCEPTIONAL_SHIELDS, ELITE_SHIELDS,
    NORMAL_SCEPTERS, EXCEPTIONAL_SCEPTERS, ELITE_SCEPTERS,
    NORMAL_ARMORS, EXCEPTIONAL_ARMORS, ELITE_ARMORS,
    NORMAL_AXES, EXCEPTIONAL_AXES, ELITE_AXES,
    NORMAL_BOWS, EXCEPTIONAL_BOWS, ELITE_BOWS, NORMAL_DAGGERS,
    NORMAL_CROSSBOWS, EXCEPTIONAL_CROSSBOWS, ELITE_CROSSBOWS,
    NORMAL_WAR_WEAPONS, EXCEPTIONAL_WAR_WEAPONS, ELITE_WAR_WEAPONS,
    NORMAL_SPEARS, EXCEPTIONAL_SPEARS, ELITE_SPEARS,
    NORMAL_SWORDS, EXCEPTIONAL_SWORDS, ELITE_SWORDS,
    NORMAL_RODS, EXCEPTIONAL_RODS, ELITE_RODS,
    NORMAL_STAFFS, EXCEPTIONAL_STAFFS, ELITE_STAFFS,
    NORMAL_MACES, EXCEPTIONAL_MACES, ELITE_MACES, NORMAL_MACES2, EXCEPTIONAL_MACES2, ELITE_MACES2, NORMAL_MACES3, EXCEPTIONAL_MACES3, ELITE_MACES3,
    NORMAL_AMAZON, EXCEPTIONAL_AMAZON, ELITE_AMAZON,
    NORMAL_ASSASIN, EXCEPTIONAL_ASSASIN, ELITE_ASSASIN,
    NORMAL_BARBARIAN, EXCEPTIONAL_BARBARIAN, ELITE_BARBARIAN,
    NORMAL_DRUID, EXCEPTIONAL_DRUID, ELITE_DRUID,
    NORMAL_SORCERER, EXCEPTIONAL_SORCERER, ELITE_SORCERER,
    NORMAL_NECROMANCER, EXCEPTIONAL_NECROMANCER, ELITE_NECROMANCER,
    NORMAL_PALADIN, EXCEPTIONAL_PALADIN, ELITE_PALADIN
    )

module.exports = {
    BASE_ITEMS
}