const NORMAL_RODS = [{"image":"http://www.d2mantix.com/diablo2img/wand.JPG","name":"Vara","originalName":"Wand","codeName":"wand","tcNumber":3,"attributes":["Daño 1 mano: 2 a 4 (3 Media) Rango (1)","Durabilidad: 15"],"itemType":"rod","itemClass":"normal","requiredLevel":1,"sockets":1},{"image":"http://www.d2mantix.com/diablo2img/yewwand.JPG","name":"Vara de Tejo","originalName":"Yew Wand","codeName":"yewwand","tcNumber":12,"attributes":["Daño 1 mano: 2 a 8 (5 Media) Rango (1)","Durabilidad: 15","Velocidad: [10]"],"itemType":"rod","itemClass":"normal","requiredLevel":1,"sockets":1},{"image":"http://www.d2mantix.com/diablo2img/bonewand.JPG","name":"Vara de Hueso","originalName":"Bone Wand","codeName":"bonewand","tcNumber":18,"attributes":["Daño 1 mano: 3 a 7 (5 Media) Rango (1)","Durabilidad: 15","Velocidad: [-20]"],"itemType":"rod","itemClass":"normal","requiredLevel":1,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/grimwand.JPG","name":"Vara Implacable","originalName":"Grim Wand","codeName":"grimwand","tcNumber":27,"attributes":["Daño 1 mano: 5 a 11 (8 Media) Rango (1)","Durabilidad: 15"],"itemType":"rod","itemClass":"normal","requiredLevel":1,"sockets":2}]

const EXCEPTIONAL_RODS = [{"image":"http://www.d2mantix.com/diablo2img/wand.JPG","name":"Vara Quemada","originalName":"Burnt Wand","codeName":"burntwand","tcNumber":33,"attributes":["Daño 1 mano: 8 a 18 (13 Media) Rango (1)","Durabilidad: 15"],"itemType":"rod","itemClass":"exceptional","requiredStrength":25,"requiredLevel":19,"sockets":1},{"image":"http://www.d2mantix.com/diablo2img/yewwand.JPG","name":"Vara Petrificada","originalName":"Petrified Wand","codeName":"petrifiedwand","tcNumber":39,"attributes":["Daño 1 mano: 8 a 24 (16 Media) Rango (1)","Durabilidad: 15","Velocidad: [10]"],"itemType":"rod","itemClass":"exceptional","requiredStrength":25,"requiredLevel":25,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/bonewand.JPG","name":"Vara de Tumba","originalName":"Tomb Wand","codeName":"tombwand","tcNumber":45,"attributes":["Daño 1 mano: 10 a 22 (16 Media) Rango (1)","Durabilidad: 15","Velocidad: [-20]"],"itemType":"rod","itemClass":"exceptional","requiredStrength":25,"requiredLevel":25,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/grimwand.JPG","name":"Vara de Tumba","originalName":"Grave Wand","codeName":"gravewand","tcNumber":51,"attributes":["Daño 1 mano: 13 a 29 (21 Media) Rango (1)","Durabilidad: 15"],"itemType":"rod","itemClass":"exceptional","requiredStrength":25,"requiredLevel":25,"sockets":2}]

const ELITE_RODS = [{"image":"http://www.d2mantix.com/diablo2img/wand.JPG","name":"La Vara Magica Pulida","originalName":"Polished Wand","codeName":"polishedwand","tcNumber":63,"attributes":["Daño 1 mano: 18 a 33 (18.5 Media) Rango (1)","Durabilidad: 15"],"itemType":"rod","itemClass":"elite","requiredStrength":25,"requiredLevel":41,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/yewwand.JPG","name":"La Vara Magica Fantasmal","originalName":"Ghost Wand","codeName":"ghostwand","tcNumber":69,"attributes":["Daño 1 mano: 20 a 42 (31 Media) Rango (1)","Durabilidad: 15","Velocidad: [10]"],"itemType":"rod","itemClass":"elite","requiredStrength":25,"requiredLevel":48,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/bonewand.JPG","name":"La Vara Magica del Camposanto","originalName":"Lich Wand","codeName":"lichwand","tcNumber":75,"attributes":["Daño 1 mano: 10 a 31 (20.5 Media) Rango (1)","Durabilidad: 15","Velocidad: [-20]"],"itemType":"rod","itemClass":"elite","requiredStrength":25,"requiredLevel":56,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/grimwand.JPG","name":"La Vara Magica Desenterrada","originalName":"Unearthed Wand","codeName":"unearthedwand","tcNumber":87,"attributes":["Daño 1 mano: 22 a 28 (25 Media) Rango (1)","Durabilidad: 15"],"itemType":"rod","itemClass":"elite","requiredStrength":25,"requiredLevel":64,"sockets":2}]

module.exports = {
    NORMAL_RODS,
    EXCEPTIONAL_RODS,
    ELITE_RODS
}