const NORMAL_SCEPTERS = [{"image":"http://www.d2mantix.com/diablo2img/scepter.JPG","name":"Cetro","originalName":"Scepter","codeName":"scepter","tcNumber":3,"attributes":["Daño 1 mano: 6 a 11 (8.5 de Media) Rango (1)","Durabilidad: 50","Velocidad: [0]"],"itemType":"scepter","itemClass":"normal","requiredStrength":25,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/grandscepter.JPG","name":"Gran Cetro","originalName":"Grand Scepter","codeName":"grandscepter","tcNumber":15,"attributes":["Daño 1 mano: 8 a 18 (13 de Media) Rango (2)","Durabilidad: 60","Velocidad: [10]"],"itemType":"scepter","itemClass":"normal","requiredStrength":37,"sockets":3},{"image":"http://www.d2mantix.com/diablo2img/warscepter.JPG","name":"Cetro de Guerra","originalName":"War Scepter","codeName":"warscepter","tcNumber":21,"attributes":["Daño 1 mano: 10 a 17 (13.5 de Media) Rango (2)","Durabilidad: 70","Velocidad: [-10]"],"itemType":"scepter","itemClass":"normal","requiredStrength":55,"sockets":5}]

const EXCEPTIONAL_SCEPTERS = [{"image":"http://www.d2mantix.com/diablo2img/scepter.JPG","name":"Cetro de Runas","originalName":"Rune Scepter","codeName":"runescepter","tcNumber":33,"attributes":["Daño 1 mano: 13 a 24 Rango (1)","Durabilidad: 50","Velocidad: [0]"],"itemType":"scepter","itemClass":"exceptional","requiredStrength":58,"requiredLevel":19,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/grandscepter.JPG","name":"Hisopo de Agua Bendita","originalName":"Holy Water Sprinkler","codeName":"holywatersprinkler","tcNumber":42,"attributes":["Daño 1 mano: 14 a 36 (25 de Media) Rango (2)","Durabilidad: 60","Velocidad: [10]"],"itemType":"scepter","itemClass":"exceptional","requiredStrength":76,"requiredLevel":25,"sockets":3},{"image":"http://www.d2mantix.com/diablo2img/warscepter.JPG","name":"Cetro Divino","originalName":"Divine Scepter","codeName":"divinescepter","tcNumber":45,"attributes":["Daño 1 mano: 16 a 38 (27 de Media) Rango (2)","Durabilidad: 70","Velocidad: [-10]"],"itemType":"scepter","itemClass":"exceptional","requiredStrength":103,"requiredLevel":25,"sockets":5}]

const ELITE_SCEPTERS = [{"image":"http://www.d2mantix.com/diablo2img/scepter.JPG","name":"El Cetro Poderoso","originalName":"Mighty Scepter","codeName":"mightyscepter","tcNumber":63,"attributes":["Daño 1 mano: 40 a 52 (46 de Media) Rango (1)","Durabilidad: 40","Velocidad: [0]"],"itemType":"scepter","itemClass":"elite","requiredStrength":125,"requiredDexterity":65,"requiredLevel":46,"sockets":2},{"image":"http://www.d2mantix.com/diablo2img/grandscepter.JPG","name":"La Vara de los Serafines","originalName":"Seraph Rod","codeName":"seraphrod","tcNumber":81,"attributes":["Daño 1 mano: 45 a 54 (49.5 de Media) Rango (2)","Durabilidad: 60","Velocidad: [10]"],"itemType":"scepter","itemClass":"elite","requiredStrength":108,"requiredDexterity":69,"requiredLevel":57,"sockets":3},{"image":"http://www.d2mantix.com/diablo2img/warscepter.JPG","name":"El Caduceo","originalName":"Caduceus","codeName":"caduceus","tcNumber":87,"attributes":["Daño 1 mano: 37 a 43 (40 de Media) Rango (2)","Durabilidad: 70","Velocidad: [-10]"],"itemType":"scepter","itemClass":"elite","requiredStrength":97,"requiredDexterity":70,"requiredLevel":66,"sockets":5}]

module.exports = {
    NORMAL_SCEPTERS,
    EXCEPTIONAL_SCEPTERS,
    ELITE_SCEPTERS
}