const NORMAL_SPEARS = [{"image":"http://www.d2mantix.com/diablo2img/spear.JPG","name":"Lanza","originalName":"Spear","codeName":"spear","tcNumber":6,"attributes":["Daño 2 manos: 3 a 15 (9 de Media) Rango (4)","Durabilidad: 30","Velocidad: [-10]"],"itemType":"spear","itemClass":"normal","sockets":3},{"image":"http://www.d2mantix.com/diablo2img/trident.JPG","name":"Tridente","originalName":"Trident","codeName":"trident","tcNumber":9,"attributes":["Daño 2 manos: 9 a 15 (12 de Media) Rango (4)","Durabilidad: 35","Velocidad: [0]"],"itemType":"spear","itemClass":"normal","requiredStrength":38,"requiredDexterity":24,"sockets":4},{"image":"http://www.d2mantix.com/diablo2img/brandistock.JPG","name":"Horca de Guerra","originalName":"Brandistock","codeName":"brandistock","tcNumber":18,"attributes":["Daño 2 manos: 7 a 17 (12 de Media) Rango (5)","Durabilidad: 28","Velocidad: [-20]"],"itemType":"spear","itemClass":"normal","requiredStrength":40,"requiredDexterity":50,"sockets":5},{"image":"http://www.d2mantix.com/diablo2img/spetum.JPG","name":"Spetum","originalName":"Spetum","codeName":"spetum","tcNumber":21,"attributes":["Daño 2 manos: 15 a 23 (19 de Media) Rango (5)","Durabilidad: 28","Velocidad: [0]"],"itemType":"spear","itemClass":"normal","requiredStrength":54,"requiredDexterity":35,"sockets":5},{"image":"http://www.d2mantix.com/diablo2img/pike.JPG","name":"Pica","originalName":"Pike","codeName":"pike","tcNumber":24,"attributes":["Daño 2 manos: 14 a 63 (38.5 de Media) Rango (5)","Durabilidad: 25","Velocidad: [20]"],"itemType":"spear","itemClass":"normal","requiredStrength":60,"requiredDexterity":45,"sockets":6}]

const EXCEPTIONAL_SPEARS = [{"image":"http://www.d2mantix.com/diablo2img/spear.JPG","name":"Lanza de Guerra","originalName":"War Spear","codeName":"warspear","tcNumber":33,"attributes":["Daño 2 manos: 10 a 37 (23.5 de Media) Rango (4)","Durabilidad: 30","Velocidad: [-10]"],"itemType":"spear","itemClass":"exceptional","requiredStrength":25,"requiredDexterity":25,"requiredLevel":21,"sockets":3},{"image":"http://www.d2mantix.com/diablo2img/trident.JPG","name":"Tridente","originalName":"Fuscina","codeName":"fuscina","tcNumber":36,"attributes":["Daño 2 manos: 19 a 37 (28 de Media) Rango (4)","Durabilidad: 35","Velocidad: [0]"],"itemType":"spear","itemClass":"exceptional","requiredStrength":77,"requiredDexterity":25,"requiredLevel":24,"sockets":4},{"image":"http://www.d2mantix.com/diablo2img/brandistock.JPG","name":"Horquilla de Guerra","originalName":"War Fork","codeName":"warfork","tcNumber":42,"attributes":["Daño 2 manos: 16 a 40 (28 de Media) Rango (5)","Durabilidad: 28","Velocidad: [-20]"],"itemType":"spear","itemClass":"exceptional","requiredStrength":80,"requiredDexterity":95,"requiredLevel":25,"sockets":5},{"image":"http://www.d2mantix.com/diablo2img/spetum.JPG","name":"Yari","originalName":"Yari","codeName":"yari","tcNumber":45,"attributes":["Daño 2 manos: 39 a 59 (49 de Media) Rango (5)","Durabilidad: 28","Velocidad: [0]"],"itemType":"spear","itemClass":"exceptional","requiredStrength":101,"requiredLevel":25,"sockets":6},{"image":"http://www.d2mantix.com/diablo2img/pike.JPG","name":"Lanza","originalName":"Lance","codeName":"lance","tcNumber":48,"attributes":["Daño 2 manos: 27 a 114 (70.5 de Media) Rango (5)","Durabilidad: 25","Velocidad: [20]"],"itemType":"spear","itemClass":"exceptional","requiredStrength":110,"requiredDexterity":88,"requiredLevel":25,"sockets":6}]

const ELITE_SPEARS = [{"image":"http://www.d2mantix.com/diablo2img/spear.JPG","name":"La Lanza de Hyperion","originalName":"Hyperion Spear","codeName":"hyperionspear","tcNumber":60,"attributes":["Daño 2 manos: 35 a 117 (77 de Media) Rango (4)","Durabilidad: 30","Velocidad: [-10]"],"itemType":"spear","itemClass":"elite","requiredStrength":155,"requiredDexterity":120,"requiredLevel":43,"sockets":3},{"image":"http://www.d2mantix.com/diablo2img/trident.JPG","name":"La Pica Estigia","originalName":"Stygian Pike","codeName":"stygianpike","tcNumber":69,"attributes":["Daño 2 manos: 29 a 144 (86.5 de Media) Rango (4)","Durabilidad: 35","Velocidad: [0]"],"itemType":"spear","itemClass":"elite","requiredStrength":168,"requiredDexterity":97,"requiredLevel":49,"sockets":4},{"image":"http://www.d2mantix.com/diablo2img/brandistock.JPG","name":"El Cazahombres","originalName":"Mancatcher","codeName":"mancatcher","tcNumber":75,"attributes":["Daño 2 manos: 42 a 92 (67 de Media) Rango (5)","Durabilidad: 28","Velocidad: [-20]"],"itemType":"spear","itemClass":"elite","requiredStrength":132,"requiredDexterity":134,"requiredLevel":55,"sockets":5},{"image":"http://www.d2mantix.com/diablo2img/spetum.JPG","name":"La Lanza Fantasmal","originalName":"Ghost Spear","codeName":"ghostspear","tcNumber":81,"attributes":["Daño 2 manos: 18 a 155 (86.5 de Media) Rango (5)","Durabilidad: 28","Velocidad: [0]"],"itemType":"spear","itemClass":"elite","requiredStrength":122,"requiredDexterity":163,"requiredLevel":62,"sockets":6},{"image":"http://www.d2mantix.com/diablo2img/pike.JPG","name":"La Pica de Guerra","originalName":"War Pike","codeName":"warpike","tcNumber":87,"attributes":["Daño 2 manos: 33 a 178 (105.5 de Media) Rango (5)","Durabilidad: 25","Velocidad: [20]"],"itemType":"spear","itemClass":"elite","requiredStrength":165,"requiredDexterity":106,"requiredLevel":86,"sockets":6}]

module.exports = {
    NORMAL_SPEARS, 
    EXCEPTIONAL_SPEARS,
    ELITE_SPEARS
}